version: '3.8'

services:
  db:
    container_name: metrics_db
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_DB: metrics_db
      POSTGRES_USER: metrics_user
      POSTGRES_PASSWORD: metrics_pass
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  app:
    container_name: metrics_app
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://metrics_user:metrics_pass@db:5432/metrics_db"
